[
    [
        "mainmenu",
        "31502",
        "widget",
        "recentchannels"
    ],
    [
        "mainmenu",
        "31502",
        "widgetName",
        "31241"
    ],
    [
        "mainmenu",
        "31502",
        "widgetType",
        ""
    ],
    [
        "mainmenu",
        "31502",
        "widgetPath",
        "pvr://channels/tv/*?view=lastplayed"
    ],
    [
        "mainmenu",
        "31502",
        "widgetTarget",
        "pvr"
    ],
    [
        "mainmenu",
        "31502",
        "widgetSortBy",
        "lastplayed"
    ],
    [
        "mainmenu",
        "31502",
        "widgetSortDirection",
        "descending"
    ],
    [
        "mainmenu",
        "31502",
        "icon",
        "special://skin/extras/icons/remote.png"
    ],
    [
        "mainmenu",
        "31502",
        "thumb",
        "DefaultAddonPVRClient.png"
    ],
    [
        "mainmenu",
        "plugin.program.advanced.emulator.launcher",
        "widget",
        "favgames"
    ],
    [
        "mainmenu",
        "plugin.program.advanced.emulator.launcher",
        "widgetName",
        "1036"
    ],
    [
        "mainmenu",
        "plugin.program.advanced.emulator.launcher",
        "widgetType",
        "programs"
    ],
    [
        "mainmenu",
        "plugin.program.advanced.emulator.launcher",
        "widgetPath",
        "plugin://plugin.program.advanced.emulator.launcher/?com=SHOW_FAVOURITES"
    ],
    [
        "mainmenu",
        "plugin.program.advanced.emulator.launcher",
        "widgetTarget",
        "programs"
    ],
    [
        "mainmenu",
        "plugin.program.advanced.emulator.launcher",
        "icon",
        "DefaultGames.png"
    ],
    [
        "mainmenu",
        "plugin.program.advanced.emulator.launcher",
        "thumb",
        "DefaultGames.png"
    ],
    [
        "mainmenu",
        "plugin.video.playlistbrowser",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.playlistbrowser\",return)"
    ],
    [
        "mainmenu",
        "plugin.video.playlistbrowser",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "plugin.video.playlistbrowser",
        "widgetName",
        "Diggz TV Guide Lite - Live TV Guide"
    ],
    [
        "mainmenu",
        "plugin.video.playlistbrowser",
        "widgetType",
        "videos"
    ],
    [
        "mainmenu",
        "plugin.video.playlistbrowser",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "plugin.video.playlistbrowser",
        "widgetPath",
        "plugin://plugin.video.playlistbrowser/?action=guide_now&src=101&reload=$INFO[Window(Home).Property(widgetreload)]$INFO[Window(Home).Property(widgetreload2)]"
    ],
    [
        "mainmenu",
        "plugin.video.playlistbrowser",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mainmenu",
        "plugin.video.playlistbrowser",
        "thumb",
        "thumb"
    ],
    [
        "mainmenu",
        "browsetvshows",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.free99/?action=tvshows_menu\",return)"
    ],
    [
        "mainmenu",
        "browsetvshows",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "browsetvshows",
        "widgetName",
        "[COLOR goldenrod]Free99[/COLOR] - Trending On Trakt"
    ],
    [
        "mainmenu",
        "browsetvshows",
        "widgetType",
        "videos"
    ],
    [
        "mainmenu",
        "browsetvshows",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "browsetvshows",
        "widgetPath",
        "plugin://plugin.video.free99/?action=tvshows&url=trakt_trending&reload=$INFO[Window(Home).Property(widgetreload-episodes)]"
    ],
    [
        "mainmenu",
        "browsetvshows",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mainmenu",
        "browsetvshows",
        "thumb",
        "image://C%3a%5cUsers%5cuser%5cAppData%5cRoaming%5cKodi%5caddons%5cscript.free99.artwork%5cresources%5cmedia%5cpurple%5ctvshows.png/"
    ],
    [
        "mainmenu",
        "browsemovies",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.free99/?action=movies_menu\",return)"
    ],
    [
        "mainmenu",
        "browsemovies",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "browsemovies",
        "widgetName",
        "[COLOR goldenrod]Free99[/COLOR] - Trending Today On Trakt"
    ],
    [
        "mainmenu",
        "browsemovies",
        "widgetType",
        "movies"
    ],
    [
        "mainmenu",
        "browsemovies",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "browsemovies",
        "widgetPath",
        "plugin://plugin.video.free99/?action=movies&url=trakt_trending&reload=$INFO[Window(Home).Property(widgetreload-movies)]"
    ],
    [
        "mainmenu",
        "browsemovies",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mainmenu",
        "browsemovies",
        "thumb",
        "image://C%3a%5cUsers%5cuser%5cAppData%5cRoaming%5cKodi%5caddons%5cscript.free99.artwork%5cresources%5cmedia%5cpurple%5cmovies.png/"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "translatedPath",
        "ActivateWindow(Music,\"plugin://plugin.audio.mp3streams\",return)"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "widgetName",
        "MP3 Streams - New Albums"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "widgetType",
        "audio"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "widgetTarget",
        "music"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "widgetPath",
        "plugin://plugin.audio.mp3streams/?url=http%3A%2F%2Fmusicmp3.ru%2Fnew_albums.html%3Fpage%3D1&mode=15&name=New+Albums&iconimage=C%3A%5CUsers%5Cuser%5CAppData%5CRoaming%5CKodi%5Caddons%5Cplugin.audio.mp3streams%5Cart%2Fallnewalbums.jpg&list=new albums<>http://musicmp3.ru/new_albums.html?page=1<>C:\\Users\\user\\AppData\\Roaming\\Kodi\\addons\\plugin.audio.mp3streams\\art/allnewalbums.jpg&type=&reload=$INFO[Window(Home).Property(widgetreload-music)]"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "thumb",
        "thumb"
    ],
    [
        "mainmenu",
        "plugin.program.iagl",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.program.iagl\",return)"
    ],
    [
        "mainmenu",
        "plugin.program.iagl",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "plugin.program.iagl",
        "widgetName",
        "Internet Archive Game Launcher - Browse all Lists"
    ],
    [
        "mainmenu",
        "plugin.program.iagl",
        "widgetType",
        "videos"
    ],
    [
        "mainmenu",
        "plugin.program.iagl",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "plugin.program.iagl",
        "widgetPath",
        "plugin://plugin.program.iagl/all?reload=$INFO[Window(Home).Property(widgetreload)]$INFO[Window(Home).Property(widgetreload2)]"
    ],
    [
        "mainmenu",
        "plugin.program.iagl",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mainmenu",
        "plugin.program.iagl",
        "thumb",
        "thumb"
    ],
    [
        "mainmenu",
        "videoappstore",
        "translatedPath",
        "ActivateWindow(10040,\"addons://all/xbmc.addon.video\",return)"
    ],
    [
        "mainmenu",
        "videoappstore",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "videoappstore",
        "widgetName",
        "EZ Maintenance+ - [COLOR white][B]MAINTENANCE[/B][/COLOR]"
    ],
    [
        "mainmenu",
        "videoappstore",
        "widgetType",
        "program"
    ],
    [
        "mainmenu",
        "videoappstore",
        "widgetTarget",
        "programs"
    ],
    [
        "mainmenu",
        "videoappstore",
        "widgetPath",
        "plugin://script.ezmaintenanceplus/?url=ur&action=maintenance&name=%5BCOLOR+white%5D%5BB%5DMAINTENANCE%5B%2FB%5D%5B%2FCOLOR%5D&icon=C%3A%5CUsers%5Cuser%5CAppData%5CRoaming%5CKodi%5Caddons%5Cscript.ezmaintenanceplus%5Cicon.png&fanart=C%3A%5CUsers%5Cuser%5CAppData%5CRoaming%5CKodi%5Caddons%5Cscript.ezmaintenanceplus%5Cfanart.jpg&description=&reload=$INFO[Window(Home).Property(widgetreload)]$INFO[Window(Home).Property(widgetreload2)]"
    ],
    [
        "mainmenu",
        "videoappstore",
        "icon",
        "DefaultFolder.png"
    ],
    [
        "mainmenu",
        "videoappstore",
        "thumb",
        "DefaultAddonVideo.png"
    ],
    [
        "mainmenu",
        "24001",
        "widget",
        "videoaddons"
    ],
    [
        "mainmenu",
        "24001",
        "widgetName",
        "1037"
    ],
    [
        "mainmenu",
        "24001",
        "widgetType",
        "movies"
    ],
    [
        "mainmenu",
        "24001",
        "widgetPath",
        "addons://sources/video/"
    ],
    [
        "mainmenu",
        "24001",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "24001",
        "widgetSortBy",
        "lastused"
    ],
    [
        "mainmenu",
        "24001",
        "widgetSortDirection",
        "descending"
    ],
    [
        "mainmenu",
        "24001",
        "icon",
        "special://skin/extras/icons/addon.png"
    ],
    [
        "mainmenu",
        "24001",
        "thumb",
        "DefaultAddon.png"
    ],
    [
        "mainmenu",
        "1036",
        "widget",
        "favorites"
    ],
    [
        "mainmenu",
        "1036",
        "widgetName",
        "1036"
    ],
    [
        "mainmenu",
        "1036",
        "widgetType",
        ""
    ],
    [
        "mainmenu",
        "1036",
        "widgetPath",
        "favourites://"
    ],
    [
        "mainmenu",
        "1036",
        "widgetTarget",
        ""
    ],
    [
        "mainmenu",
        "1036",
        "icon",
        "special://skin/extras/icons/favourite.png"
    ],
    [
        "mainmenu",
        "1036",
        "thumb",
        "DefaultIconFavourite.png"
    ],
    [
        "mainmenu",
        "weather",
        "widget",
        "weather"
    ],
    [
        "mainmenu",
        "weather",
        "widgetName",
        "12600"
    ],
    [
        "mainmenu",
        "weather",
        "icon",
        "special://skin/extras/icons/weather.png"
    ],
    [
        "mainmenu",
        "weather",
        "thumb",
        "DefaultAddonWeather.png"
    ],
    [
        "mainmenu",
        "137",
        "widget",
        "myplaylists"
    ],
    [
        "mainmenu",
        "137",
        "widgetName",
        "136"
    ],
    [
        "mainmenu",
        "137",
        "widgetType",
        "videos"
    ],
    [
        "mainmenu",
        "137",
        "widgetPath",
        "special://videoplaylists/"
    ],
    [
        "mainmenu",
        "137",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "137",
        "widgetIcon",
        "20445"
    ],
    [
        "mainmenu",
        "137",
        "icon",
        "DefaultIconSearch.png"
    ],
    [
        "mainmenu",
        "137",
        "thumb",
        "DefaultIconSearch.png"
    ],
    [
        "mainmenu",
        "5",
        "widget",
        "settings"
    ],
    [
        "mainmenu",
        "5",
        "widgetName",
        "5"
    ],
    [
        "mainmenu",
        "5",
        "icon",
        "DefaultIconSettings.png"
    ],
    [
        "mainmenu",
        "5",
        "thumb",
        "DefaultIconSettings.png"
    ]
]